# Generated by Django 4.2.6 on 2025-01-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0003_incident_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationsParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainResource', models.TextField()),
                ('type', models.CharField(choices=[('SMS', 'SMS'), ('TELEGRAM', 'TELEGRAM'), ('EMAIL', 'EMAIL'), ('WHATSAPP', 'WHATSAPP')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications_parameters',
            },
        ),
        migrations.AddConstraint(
            model_name='notificationsparameters',
            constraint=models.UniqueConstraint(fields=('type', 'mainResource'), name='unique_type_resource'),
        ),
    ]
